version: "2"
services:
  app:
    container_name: docker-node
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
  mongodb:
    container_name: docker-mongo
    image: mongo
    ports:
      - "28017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
